#
# Core service configuration
#
logging.path: ./
logging.file: myapp.log

#
# Server configuration
#

server.address: 0.0.0.0
server.port: 9090
#server.sessionTimeout:

upload.max.size: 10000000
heartbeat.interval: 10000
scheduler.pool.size: 100

#
# Server production management/monitoring configuration
# server management URL
#   http://<management.address>:<management.port>/<mangement.context_path>/<endpoint name>
# JMX management URL
#   http://<management.address>:<management.port>/<mangement.context_path>/jolokia
#
security.basic.enabled: false
security.user.name: admin
security.user.password: password

endpoint.health.enabled: true
endpoint.autoconfig: true
endpoint.dump: true
endpoint.metrics: true
endpoint.configprops: true
endpoint.beans: true
endpoint.trace: true
endpoint.mappings: true
            
management.security.enabled: false
management.security.role: SUPERUSER
management.context-path: /manage
management.port: 8083
